import type { Metadata } from "next";
import "@/styles/normalize.css";
import "@/styles/variables.css";
import "@/styles/globals.css";
import Sidebar from "@/components/Sidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <main className="bg-bgPrimary h-full flex flex-row">
          <Sidebar />
          {children}
        </main>
      </body>
    </html>
  );
}
